// Generated by CoffeeScript 1.7.1
(function() {
  var util;

  util = require('util');

  module.exports = function(robot) {
    robot.respond(/FAKE EVENT (.*)/i, function(msg) {
      msg.send("fake event '" + msg.match[1] + "' triggered");
      return robot.emit(msg.match[1], {
        user: msg.message.user
      });
    });
    return robot.on('debug', function(event) {
      return robot.send(event.user, util.inspect(event));
    });
  };

}).call(this);

//# sourceMappingURL=events.map
